### ISSUE TITLE
Can't delete folders from webmail

### ISSUE THREAD

**Issue by sahsanu** [vontainment/v-hestiacp-sieve#11]
Hello,

Today I was migrating some accounts to my new hestiacp server and when I tried to delete a folder from webmail (roundcube) I got an error (Internal Error) and the folder isn't deleted.

Checking dovecot log I saw the real error:

`Jul 27 19:22:08 imap(postmaster@example.com)<348329><NvExNHsBGqkAAAAAAAAAAAAAAAAAAAAB>: Error: Mailbox spam: Dict private transaction commit failed: dict-file: file_dotlock_open(/home/master/dovecot-attributes) failed: Permission denied`

postmaster@example.com is the user's mail, spam is the folder I tried to delete and /home/master/ is the home of the hestiacp user. As you can see, seems dovecot fails to create file **/home/master/dovecot-attributes** and after that I saw the conf in 20-spamham.conf and there was the problem, the directive **mail_attribute_dict** is configured to use a wrong home for the mail user (in hestiacp).

I've changed it with the right path for hestiacp mail users and it is working fine, it is copying spam and ham mails and no errors when I try to delete the folder.

Tonight or maybe tomorrow I'll send a pull request to fix this issue.

**Comment by vontainment** [comment]
Ty
