### ISSUE TITLE
imapsieve_copy uses the "spam" and "ham" directories, but they were never created

### ISSUE THREAD

**Issue by ClayRabbit** [vontainment/v-hestiacp-sieve#3]
**/var/log/dovecot.log**:
Nov 07 12:30:48 imap: Error: /etc/dovecot/sieve/imapsieve_copy: line 11: /var/mail/imapsieve_copy/spam/info@...-20221107123048-57489138.eml: No such file or directory
Nov 07 12:30:48 imap(info@...)<1655801><2DUoFN7snNN/AAAB>: Error: program exec:/etc/dovecot/sieve/imapsieve_copy (1655805): write(program stdin) failed: Broken pipe
Nov 07 12:30:48 imap(info@...)<1655801><2DUoFN7snNN/AAAB>: Error: sieve: failed to pipe message to program `imapsieve_copy': refer to server log for more information. [2022-11-07 12:30:48]
Nov 07 12:30:48 imap(info@...)<1655801><2DUoFN7snNN/AAAB>: Error: sieve: Execution of script /var/mail/sieve/report_spam.sieve failed

**Comment by vontainment** [comment]
I'll make some changes to create them ty
